Add actions for notifying of failure & success

diff --git a/.github/workflows/notify_failure.yml b/.github/workflows/notify_failure.yml
--- a/.github/workflows/notify_failure.yml
+++ b/.github/workflows/notify_failure.yml
@@ -1,4 +1,4 @@
-name: Test Discord notification on Push to Test
+name: Simulate a failing job and send a notification to Discord
 
 on:
   push:
@@ -15,6 +15,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Simulate a failing job
+        run: |
+          echo "This job will fail"
+          exit 1
+
       - uses: actions/setup-ruby@v1
       - name: Send Webhook Notification
         if: always()
@@ -24,6 +29,6 @@ jobs:
           HOOK_OS_NAME: ${{ runner.os }}
           WORKFLOW_NAME: ${{ github.workflow }}
         run: |
-          git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
+          git clone https://github.com/elendil7/github-actions-discord-webhook webhook
           bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
         shell: bash
